# Generated by Django 5.2.7 on 2025-11-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBC_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='label_raw',
            field=models.CharField(blank=True, help_text='Original extracted label from OCR', max_length=255, null=True),
        ),
    ]
