# Generated by Django 5.2.8 on 2025-11-16 06:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBC_App', '0003_testinterpretation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, help_text='Optional message from patient', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('responded', 'Responded'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reports_received', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_reports', to='CBC_App.uploaddocument')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reports_sent', to=settings.AUTH_USER_MODEL)),
                ('tests', models.ManyToManyField(blank=True, related_name='shared_in_reports', to='CBC_App.testresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visible_to_patient', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('shared_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='CBC_App.sharedreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
