# Generated by Django 5.2.8 on 2025-11-16 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBC_App', '0004_sharedreport_doctorrecommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testinterpretation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='uploaddocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='uploaddocument',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='uploaddocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
